### PR TITLE
Mattermost fixes and multiple param support

### LINKED ISSUE #68: Mattermost Bug: query with all spaces leads to Server Error
`/yals   ` leads to reply :warning: Server Error

### PR DESCRIPTION
**Pull request by kyberorg**
* Fix #68 Mattermost Bug: query with all spaces leaded to ":warning: Server Error"
* New #69 Mattermost: multiple param support 
* New #70 :warning: replaced with  :information_source: in Usage message

### CODE REVIEW

File: src/main/java/ee/yals/json/MattermostResponseJson.java [hunk 1]
```diff
@@ -37,11 +37,12 @@ public static MattermostResponseJson createWithText(String text) {
...
         boolean containsUrl = UrlExtraValidator.isStringContainsUrl(text);
         boolean isErrorMessage = text.contains(Emoji.WARNING);
-        if (containsUrl || isErrorMessage) {
+        boolean isUsageMessage = (text.contains(Emoji.INFO) && text.contains("Usage"));
+        if (containsUrl || isErrorMessage || isUsageMessage) {
             mmJson.text = text;
             return mmJson;
         } else {
-            throw new IllegalArgumentException("Text must be either: valid URL or error message");
+            throw new IllegalArgumentException("Text must be either: valid URL, usage error message");
```
Comment (kyberorg) [inline src/main/java/ee/yals/json/MattermostResponseJson.java]: where is "or" ?
